version: 2
jobs:
  build:
    working_directory: ~/Social-Network-For_Cooks-Client
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --force
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
